// src/app/components/layout/AdminLayout.vue
<template>
  <div class="flex h-screen bg-gray-100">
    <!-- Sidebar -->
    <aside class="w-64 bg-white shadow">
      <div class="p-6">
        <h1 class="text-2xl font-bold text-gray-900">Museum Admin</h1>
      </div>
      <nav class="mt-6">
        <router-link
          v-if="auth.can('dashboard.read')"
          to="/admin/dashboard"
          class="block px-6 py-2 text-gray-700 hover:bg-gray-100"
          active-class="bg-blue-50 text-blue-600 border-r-4 border-blue-600"
        >
          Dashboard
        </router-link>
        <router-link
          v-if="auth.can('exhibits.read')"
          to="/admin/exhibits"
          class="block px-6 py-2 text-gray-700 hover:bg-gray-100"
          active-class="bg-blue-50 text-blue-600 border-r-4 border-blue-600"
        >
          Exhibits
        </router-link>
        <router-link
          v-if="auth.can('media.read')"
          to="/admin/media"
          class="block px-6 py-2 text-gray-700 hover:bg-gray-100"
          active-class="bg-blue-50 text-blue-600 border-r-4 border-blue-600"
        >
          Media
        </router-link>
        <router-link
          v-if="auth.can('halls.read')"
          to="/admin/halls"
          class="block px-6 py-2 text-gray-700 hover:bg-gray-100"
          active-class="bg-blue-50 text-blue-600 border-r-4 border-blue-600"
        >
          Halls
        </router-link>
        <router-link
          v-if="auth.can('exhibits.read')"
          to="/admin/review"
          class="block px-6 py-2 text-gray-700 hover:bg-gray-100"
          active-class="bg-blue-50 text-blue-600 border-r-4 border-blue-600"
        >
          Review
        </router-link>
        <router-link
          v-if="auth.can('audit.read')"
          to="/admin/audit"
          class="block px-6 py-2 text-gray-700 hover:bg-gray-100"
          active-class="bg-blue-50 text-blue-600 border-r-4 border-blue-600"
        >
          Audit
        </router-link>
        <router-link
          v-if="auth.can('audit.read')"
          to="/admin/analytics"
          class="block px-6 py-2 text-gray-700 hover:bg-gray-100"
          active-class="bg-blue-50 text-blue-600 border-r-4 border-blue-600"
        >
          Analytics
        </router-link>
        <button
          @click="handleLogout"
          class="w-full text-left px-6 py-2 text-gray-700 hover:bg-gray-100"
        >
          Logout
        </button>
      </nav>
    </aside>

    <!-- Main content -->
    <div class="flex-1 flex flex-col overflow-hidden">
      <!-- Top bar -->
      <header class="bg-white shadow">
        <div class="px-6 py-4 flex justify-between items-center">
          <h2 class="text-xl font-semibold text-gray-900">
            <slot name="title">Page</slot>
          </h2>
          <div class="text-sm text-gray-500">
            <slot name="user-info">
              {{ auth.user?.email || 'Admin User' }}
            </slot>
          </div>
        </div>
      </header>

      <!-- Page content -->
      <main class="flex-1 overflow-auto">
        <div class="p-6">
          <slot />
        </div>
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router'
import { useAuth } from '../../composables/useAuth'

const router = useRouter()
const auth = useAuth()

const handleLogout = () => {
  auth.logout()
  router.push('/admin/login')
}
</script>

// src/app/components/admin-layout.tsx
import { ReactNode, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router';
import { Moon, Sun, Menu, X, LayoutDashboard, Package, Image, Building2, LogOut } from 'lucide-react';
import { Button } from './ui/button';
import { useTheme } from './theme-provider';

interface AdminLayoutProps {
  children: ReactNode;
}

export default function AdminLayout({ children }: AdminLayoutProps) {
  const { theme, setTheme } = useTheme();
  const location = useLocation();
  const navigate = useNavigate();
  const [sidebarOpen, setSidebarOpen] = useState(false);

  const navItems = [
    { icon: LayoutDashboard, label: 'Dashboard', path: '/admin/dashboard' },
    { icon: Package, label: 'Экспонаты', path: '/admin/exhibits' },
    { icon: Image, label: 'Медиа', path: '/admin/media' },
    { icon: Building2, label: 'Залы', path: '/admin/halls' },
  ];

  const handleLogout = () => {
    navigate('/admin/login');
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Top bar */}
      <header className="sticky top-0 z-20 bg-card border-b border-border">
        <div className="flex items-center justify-between h-16 px-4">
          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              size="icon"
              className="lg:hidden"
              onClick={() => setSidebarOpen(!sidebarOpen)}
            >
              {sidebarOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
            </Button>
            <h1 className="text-xl font-semibold">Админ-панель музея</h1>
          </div>
          <div className="flex items-center gap-2">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}
            >
              {theme === 'dark' ? <Sun className="w-5 h-5" /> : <Moon className="w-5 h-5" />}
            </Button>
            <Button variant="ghost" size="icon" onClick={handleLogout}>
              <LogOut className="w-5 h-5" />
            </Button>
          </div>
        </div>
      </header>

      <div className="flex">
        {/* Sidebar */}
        <aside
          className={`fixed lg:static inset-y-0 left-0 z-10 w-64 bg-sidebar border-r border-sidebar-border transition-transform lg:translate-x-0 ${
            sidebarOpen ? 'translate-x-0' : '-translate-x-full'
          }`}
        >
          <nav className="flex flex-col gap-2 p-4 mt-16 lg:mt-0">
            {navItems.map((item) => {
              const Icon = item.icon;
              const isActive = location.pathname === item.path;
              return (
                <Link
                  key={item.path}
                  to={item.path}
                  className={`flex items-center gap-3 px-4 py-3 rounded-lg transition-colors ${
                    isActive
                      ? 'bg-sidebar-accent text-sidebar-accent-foreground'
                      : 'text-sidebar-foreground hover:bg-sidebar-accent/50'
                  }`}
                  onClick={() => setSidebarOpen(false)}
                >
                  <Icon className="w-5 h-5" />
                  <span>{item.label}</span>
                </Link>
              );
            })}
          </nav>
        </aside>

        {/* Overlay for mobile */}
        {sidebarOpen && (
          <div
            className="fixed inset-0 bg-black/50 z-0 lg:hidden"
            onClick={() => setSidebarOpen(false)}
          />
        )}

        {/* Main content */}
        <main className="flex-1 p-4 lg:p-8">
          <div className="max-w-7xl mx-auto">{children}</div>
        </main>
      </div>
    </div>
  );
}
